ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP1()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_13 = -(MDL_COSXI*MDL_CTH*MDL_COMPLEXI*MDL_GG)
      GC_55 = MDL_CTH*MDL_GG*MDL_SINXI
      GC_58 = -(MDL_COSXI*MDL_COMPLEXI*MDL_GG*MDL_STH)
      GC_61 = MDL_GG*MDL_SINXI*MDL_STH
      GC_137 = -(MDL_CTH__EXP__3*MDL_COMPLEXI*MDL_LAM3)-3.000000D+00
     $ *MDL_CTH*MDL_COMPLEXI*MDL_LAM1*MDL_STH__EXP__2+6.000000D+00
     $ *MDL_CTH__EXP__2*MDL_COMPLEXI*MDL_LAM2*MDL_STH*MDL_VEV
     $ -MDL_CTH__EXP__3*MDL_COMPLEXI*MDL_LAM4*MDL_VS-6.000000D+00
     $ *MDL_CTH*MDL_COMPLEXI*MDL_LAM2*MDL_STH__EXP__2*MDL_VS
      GC_139 = 2.000000D+00*MDL_CTH__EXP__2*MDL_COMPLEXI*MDL_LAM1
     $ *MDL_STH-MDL_CTH__EXP__2*MDL_COMPLEXI*MDL_LAM3*MDL_STH
     $ -MDL_COMPLEXI*MDL_LAM1*MDL_STH__EXP__3-2.000000D+00
     $ *MDL_CTH__EXP__3*MDL_COMPLEXI*MDL_LAM2*MDL_VEV+4.000000D+00
     $ *MDL_CTH*MDL_COMPLEXI*MDL_LAM2*MDL_STH__EXP__2*MDL_VEV
     $ +4.000000D+00*MDL_CTH__EXP__2*MDL_COMPLEXI*MDL_LAM2*MDL_STH
     $ *MDL_VS-MDL_CTH__EXP__2*MDL_COMPLEXI*MDL_LAM4*MDL_STH*MDL_VS
     $ -2.000000D+00*MDL_COMPLEXI*MDL_LAM2*MDL_STH__EXP__3*MDL_VS
      GC_143 = (MDL_COMPLEXI*MDL_STH*MDL_YB)/MDL_SQRT__2
      END
