ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SFDM_Gev_excess'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_13 = ', GC_13
      WRITE(*,2) 'GC_55 = ', GC_55
      WRITE(*,2) 'GC_58 = ', GC_58
      WRITE(*,2) 'GC_61 = ', GC_61
      WRITE(*,2) 'GC_137 = ', GC_137
      WRITE(*,2) 'GC_139 = ', GC_139
      WRITE(*,2) 'GC_170 = ', GC_170
