C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Identity(2,1)*Identity(4,3)*Identity(6,5)
C     
      SUBROUTINE FFFFFF1_0(F1, F2, F3, F4, F5, F6, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 F3(*)
      COMPLEX*16 F4(*)
      COMPLEX*16 F5(*)
      COMPLEX*16 F6(*)
      COMPLEX*16 TMP0
      COMPLEX*16 TMP1
      COMPLEX*16 TMP2
      COMPLEX*16 VERTEX
      TMP0 = (F6(3)*F5(3)+F6(4)*F5(4)+F6(5)*F5(5)+F6(6)*F5(6))
      TMP1 = (F4(3)*F3(3)+F4(4)*F3(4)+F4(5)*F3(5)+F4(6)*F3(6))
      TMP2 = (F2(3)*F1(3)+F2(4)*F1(4)+F2(5)*F1(5)+F2(6)*F1(6))
      VERTEX = COUP*(-CI * TMP0*TMP1*TMP2)
      END


